{
 "title": "OPCUA Servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "OPCUA_Srv_All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"value1\"\nFROM my_table\nWHERE\n  $__timeFilter(time) AND\n  host='myDp1.int'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"value2\"\nFROM my_table\nWHERE\n  $__timeFilter(time) AND\n  host='myDp2.int'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"value3\"\nFROM my_table\nWHERE\n  $__timeFilter(time) AND\n  host='myDp3.int'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv1_int",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp1.int'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv1_bit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp1.bool'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv2_int",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp2.int'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv2_bit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp2.bool'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv3_int",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp3.int'\nORDER BY time"
    }
   ]
  },
  {
   "title": "OPCUA_Srv3_bit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM my_table\nWHERE\n  $__timeFilter(time) AND host = 'myDp3.bool'\nORDER BY time"
    }
   ]
  }
 ]
}