version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_Password}
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080